'use client';
import React, {useEffect} from "react";
import "./css/style.css";

import { Inter, Lexend, Amatic_SC } from "next/font/google";

import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

import AOS from "aos";
import "aos/dist/aos.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  display: "swap",
});

const amatic = Amatic_SC({
    subsets: ['latin',"hebrew"],
    variable: "--font-amatic",
    display: "swap",
    style: 'normal',
    weight: "700",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
    useEffect(() => {
        AOS.init({
            once: true,
            disable: "phone",
            duration: 700,
            easing: "ease-out-cubic",
        });
    });

  return (
    <html lang="en" className={`scroll-smooth`}>
      <body
        className={`${lexend.variable} ${amatic.variable} bg-green-50 font-lexend tracking-tight text-gray-900 antialiased`}
      >
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">

            <Header />

            <main className="grow">{children}</main>

            <Footer border={true} />
        </div>
      </body>
    </html>
  );
}
